version: '3'
services:
  fabric-sdk-server:
    build: ../../
    ports:
      - "8080:8080"
    volumes:
      - ./${FSD_KEYSTORE_PATH}:/go/keystore
      - ./${FSD_CONFIG_PATH}:/config
    environment:
      FABSRV_SERVER_ADDRESS: 0.0.0.0
      FABSRV_FABRIC_CONFIGPATH: "/config/${FSD_CONFIG_FILENAME}"
  fabric-sdk-fe:
    image: nginx:1.15.8-alpine
    ports:
      - "8090:80"
    volumes:
      - ../../fe:/usr/share/nginx/html
      - ${PWD}/config.js:/usr/share/nginx/html/config.js
      - ${PWD}/../../nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
