version: '3'
services:
  fabric-sdk-server-org1:
    build: ../../
    ports:
      - "8081:8080"
    volumes:
      - ../../keystore:/go/keystore
      - ../../config/org1:/config
    environment:
      FABSRV_SERVER_ADDRESS: 0.0.0.0
      FABSRV_FABRIC_CONFIGPATH: "/config/sdk_config.yaml"
  fabric-sdk-fe-org1:
    image: nginx:1.15.8-alpine
    ports:
      - "8091:80"
    volumes:
      - ../../fe:/usr/share/nginx/html
      - ./config-org1.js:/usr/share/nginx/html/config.js
      - ../../nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
  fabric-sdk-server-org2:
    build: ../../
    ports:
      - "8082:8080"
    volumes:
      - ../../keystore:/go/keystore
      - ../../config/org2:/config
    environment:
      FABSRV_SERVER_ADDRESS: 0.0.0.0
      FABSRV_FABRIC_CONFIGPATH: "/config/sdk_config.yaml"
  fabric-sdk-fe-org2:
    image: nginx:1.15.8-alpine
    ports:
      - "8092:80"
    volumes:
      - ../../fe:/usr/share/nginx/html
      - ./config-org2.js:/usr/share/nginx/html/config.js
      - ../../nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]